[book]
authors = ["ns", "TheBlackParrot", "Pecon", "Sixmorphugus", "DessertSource", "maxymax13"]
language = "en"
multilingual = false
src = "src"
title = "Brickadia Manual"

# from mdbook-image-size
[preprocessor.image-size]
command = "mdbook-image-size"