[book]
authors = ["ns", "TheBlackParrot", "Pecon", "Sixmorphugus", "DessertSource", "maxymax13"]
language = "en"
multilingual = false
src = "src"
title = "Brickadia Manual"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/DessertSource/book/tree/main"
edit-url-template = "https://github.com/DessertSource/book/edit/main/{path}"

[output.html.fold]
enable = true
level = 4

# from mdbook-image-size
[preprocessor.image-size]
command = "mdbook-image-size"