[book]
authors = ["ns", "TheBlackParrot", "Pecon", "Sixmorphugus", "DessertSource", "maxymax13"]
language = "en"
multilingual = false
src = "src"
title = "Brickadia Manual"

[output.html]
no-section-label = true

[output.html.fold]
enable = true
level = 4