name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.40'

      - name: Install mdbook-admonish from git
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-admonish
          git: https://github.com/tommilligan/mdbook-admonish

      - run: mdbook-admonish install ./

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          force_orphan: true